services:
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - REDIS_HOST=redis
      - PORT=3000
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - 4173:4173
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
