services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
